# Generated by Django 5.2.8 on 2025-11-28 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название песни')),
                ('duration', models.DurationField(verbose_name='время')),
                ('songer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.singer', verbose_name='Исполнитель')),
            ],
        ),
    ]
